#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

SQLITE_VERSION="${SQLITE_VERSION:-3.53.4}"
SQLITE_RELEASE_ID="${SQLITE_RELEASE_ID:-3530400}"
SQLITE_YEAR="${SQLITE_YEAR:-2026}"
SQLITE_SOURCE_SHA3="${SQLITE_SOURCE_SHA3:-b834d474b9b393d85a9e3ee4cc11f1329e007e9376a424ee740796f5c4bda3a8}"
SQLITE_SOURCE_URL="${SQLITE_SOURCE_URL:-https://www.sqlite.org/${SQLITE_YEAR}/sqlite-src-${SQLITE_RELEASE_ID}.zip}"
WORK_DIR="${SQLITE_BUILD_WORK_DIR:-$PROJECT_ROOT/.tmp/sqlite-build-${SQLITE_RELEASE_ID}}"
JOBS="${JOBS:-$(getconf _NPROCESSORS_ONLN 2>/dev/null || echo 2)}"

ORIGINAL_DIR="$PROJECT_ROOT/install/sqlite3-original-build"
STRIPPED_DIR="$PROJECT_ROOT/install/sqlite3"
TOOLS=(sqlite3 sqldiff sqlite3_analyzer sqlite3_rsync)

log() { printf '[sqlite-build] %s\n' "$*"; }
die() { printf '[sqlite-build] ERROR: %s\n' "$*" >&2; exit 1; }
need() { command -v "$1" >/dev/null 2>&1 || die "Missing command: $1"; }

for cmd in curl unzip make gcc openssl strip file ldd sha256sum readelf tclsh; do
  need "$cmd"
done

if ! openssl dgst -list 2>/dev/null | grep -q -- '-sha3-256'; then
  die "The current OpenSSL does not support SHA3-256"
fi

rm -rf "$WORK_DIR"
mkdir -p "$WORK_DIR/download" "$WORK_DIR/source"
archive="$WORK_DIR/download/sqlite-src-${SQLITE_RELEASE_ID}.zip"

log "Downloading $SQLITE_SOURCE_URL"
curl --fail --location --retry 3 --output "$archive" "$SQLITE_SOURCE_URL"

actual_sha3="$(openssl dgst -sha3-256 "$archive" | awk '{print $NF}')"
[[ "$actual_sha3" == "$SQLITE_SOURCE_SHA3" ]] || \
  die "SHA3-256 mismatch: expected=$SQLITE_SOURCE_SHA3 actual=$actual_sha3"

unzip -q "$archive" -d "$WORK_DIR/source"
src="$WORK_DIR/source/sqlite-src-${SQLITE_RELEASE_ID}"
[[ -x "$src/configure" ]] || die "configure was not found at $src"

cd "$src"

# Keep debug information in the original build. GNU Readline is enabled to reproduce
# the interactive behavior of the current binary bundle. Distributing a sqlite3 executable
# linked with Readline must comply with the applicable GPL obligations.
export CFLAGS="${CFLAGS:--O2 -g -fPIC -fstack-protector-strong -fstack-clash-protection -fcf-protection}"
export CPPFLAGS="${CPPFLAGS:-}"
export LDFLAGS="${LDFLAGS:-}"

configure_help="$(./configure --help 2>&1 || true)"
configure_args=()
if grep -q -- '--enable-readline' <<<"$configure_help"; then
  configure_args+=(--enable-readline)
fi

./configure "${configure_args[@]}"
make -j "$JOBS" "${TOOLS[@]}"

if ! ldd "$src/sqlite3" 2>/dev/null | grep -q 'libreadline'; then
  die "sqlite3 is not linked with GNU Readline. Install libreadline-dev/readline-devel and run again."
fi

for tool in "${TOOLS[@]}"; do
  [[ -x "$src/$tool" ]] || die "The build did not produce $tool"
done

stage_original="$WORK_DIR/original"
stage_stripped="$WORK_DIR/stripped"
mkdir -p "$stage_original" "$stage_stripped"

for tool in "${TOOLS[@]}"; do
  install -m 0755 "$src/$tool" "$stage_original/$tool"
  install -m 0755 "$src/$tool" "$stage_stripped/$tool"
  strip --strip-unneeded "$stage_stripped/$tool"
done

write_info() {
  local dir="$1" kind="$2"
  local cli_version compiler
  cli_version="$($dir/sqlite3 --version)"
  compiler="$(readelf -p .comment "$stage_original/sqlite3" 2>/dev/null | sed -n 's/.*]  //p' | head -n1 || true)"
  cat > "$dir/BUILD-INFO.txt" <<INFO
Bundled SQLite tools - $kind
Generated by: scripts/rebuild-sqlite-tools.sh
SQLite source version: $SQLITE_VERSION
SQLite source archive: sqlite-src-$SQLITE_RELEASE_ID.zip
SQLite source URL: $SQLITE_SOURCE_URL
SQLite source SHA3-256: $SQLITE_SOURCE_SHA3
Architecture: $(uname -m)
SQLite CLI version: $cli_version
Compiler: ${compiler:-unknown}
CFLAGS: $CFLAGS

Notes:
- Linux dynamically linked binaries.
- sqlite3 is configured with GNU Readline support.
- Host shared libraries/glibc must remain ABI-compatible.
- SHA-256 checksums are stored in SHA256SUMS.
INFO
  (
    cd "$dir"
    sha256sum "${TOOLS[@]}" > SHA256SUMS
  )
}

write_info "$stage_original" "original non-stripped build"
write_info "$stage_stripped" "stripped build"

rm -rf "$ORIGINAL_DIR.new" "$STRIPPED_DIR.new"
mv "$stage_original" "$ORIGINAL_DIR.new"
mv "$stage_stripped" "$STRIPPED_DIR.new"
rm -rf "$ORIGINAL_DIR" "$STRIPPED_DIR"
mv "$ORIGINAL_DIR.new" "$ORIGINAL_DIR"
mv "$STRIPPED_DIR.new" "$STRIPPED_DIR"

log "Updated:"
log "  $ORIGINAL_DIR"
log "  $STRIPPED_DIR"
log "Run the MANIFEST.sha256 generation script again before release."
